spring:
  application:
    name: cloud-server-config
  cloud:
    config:
      server:
        git:
          #GIT仓库地址
          uri: https://github.com/yst6857/spring-cloud-demo.git
          #配置仓库路径下相对搜索位置，可配置多个
          search-paths: config-repo
          #访问GIT仓库的用户名
          username: yangst6857@163.com
          #访问GIT仓库的用户密码
          password: yst904530

server:
  port: 8083


#spring.cloud.config.server.health.repositories.check.name=configclient
#spring.cloud.config.server.health.repositories.check.label=master
#spring.cloud.config.server.health.repositories.check.profiles=dev
#关闭健康检查
#spring.cloud.config.server.health.enabled=false

#spring.cloud.config.username=user
#spring.cloud.config.password=37cc5635-559b-4e6f-b633-7e932b813f73

#eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8080/eureka/
#,http://localhost:1112/eureka/